#!/usr/bin/env python3
"""Inventory res:// dependencies used by the Cyber City Platformer project."""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path


SCAN_SUFFIXES = {".gd", ".json", ".tres", ".tscn"}
PATH_PATTERN = re.compile(r"res://[^\"'\r\n]+")
TRAILING_TOKENS = " \t,;)]}"


@dataclass
class Dependency:
    path: str
    references: list[dict[str, object]] = field(default_factory=list)
    hard_reference: bool = False


def git_lines(root: Path, *arguments: str) -> set[str]:
    result = subprocess.run(
        ["git", "-c", "core.quotepath=false", *arguments],
        cwd=root,
        check=True,
        capture_output=True,
        text=True,
        encoding="utf-8",
    )
    return {line.replace("\\", "/") for line in result.stdout.splitlines() if line}


def is_editor_source(source: str) -> bool:
    normalized = source.replace("\\", "/")
    return normalized.startswith(("addons/", "tools/", "scripts/tools/"))


def collect_dependencies(root: Path, tracked: set[str]) -> dict[str, Dependency]:
    dependencies: dict[str, Dependency] = {}
    for source in sorted(root.rglob("*")):
        if not source.is_file() or ".git" in source.parts or ".godot" in source.parts:
            continue
        relative_parts = source.relative_to(root).parts
        if relative_parts and relative_parts[0] == "docs":
            continue
        if len(relative_parts) >= 2 and relative_parts[:2] == ("assets", "runtime"):
            continue
        if source.name != "project.godot" and source.suffix.lower() not in SCAN_SUFFIXES:
            continue
        relative_source = source.relative_to(root).as_posix()
        if relative_source not in tracked:
            continue
        try:
            lines = source.read_text(encoding="utf-8-sig").splitlines()
        except UnicodeDecodeError:
            continue
        for line_number, line in enumerate(lines, 1):
            for match in PATH_PATTERN.finditer(line):
                resource_path = match.group(0).rstrip(TRAILING_TOKENS)
                if not resource_path or resource_path == "res://":
                    continue
                dependency = dependencies.setdefault(resource_path, Dependency(resource_path))
                context = line.strip()
                hard = (
                    "preload(" in context
                    or "ext_resource" in context.lower()
                    or "run/main_scene" in context
                    or relative_source == "project.godot"
                )
                dependency.hard_reference = dependency.hard_reference or hard
                dependency.references.append(
                    {"source": relative_source, "line": line_number, "hard": hard}
                )
    return dependencies


def classify(
    root: Path,
    dependency: Dependency,
    tracked: set[str],
    ignored: set[str],
) -> dict[str, object]:
    relative_path = dependency.path.removeprefix("res://")
    normalized = relative_path.replace("\\", "/")
    present = (root / Path(relative_path)).exists()
    is_directory = (root / Path(relative_path)).is_dir()
    is_tracked = normalized in tracked or (
        is_directory and any(path.startswith(normalized.rstrip("/") + "/") for path in tracked)
    )
    is_ignored = normalized in ignored or (
        is_directory and any(path.startswith(normalized.rstrip("/") + "/") for path in ignored)
    )
    all_editor = all(is_editor_source(str(ref["source"])) for ref in dependency.references)

    if present and is_tracked:
        distribution = "Present and tracked"
    elif present and is_ignored:
        distribution = "Present but ignored"
    elif present:
        distribution = "Present but untracked"
    else:
        distribution = "Missing"

    if all_editor:
        requirement = "Editor-only"
    elif dependency.hard_reference:
        requirement = "Runtime-critical"
    else:
        requirement = "Optional"

    return {
        "path": dependency.path,
        "distribution": distribution,
        "requirement": requirement,
        "present": present,
        "tracked": is_tracked,
        "ignored": is_ignored,
        "hard_reference": dependency.hard_reference,
        "references": dependency.references,
    }


def markdown_report(records: list[dict[str, object]]) -> str:
    distribution_counts: dict[str, int] = defaultdict(int)
    requirement_counts: dict[str, int] = defaultdict(int)
    blockers: list[dict[str, object]] = []
    for record in records:
        distribution_counts[str(record["distribution"])] += 1
        requirement_counts[str(record["requirement"])] += 1
        if record["requirement"] == "Runtime-critical" and not record["tracked"]:
            blockers.append(record)

    lines = [
        "# Runtime asset inventory",
        "",
        "Generated by `python tools/inventory_runtime_assets.py`.",
        "",
        "## Summary",
        "",
        f"- Unique `res://` dependencies: {len(records)}",
        f"- Runtime-critical dependencies not tracked: {len(blockers)}",
    ]
    for key in sorted(distribution_counts):
        lines.append(f"- {key}: {distribution_counts[key]}")
    for key in sorted(requirement_counts):
        lines.append(f"- {key}: {requirement_counts[key]}")

    lines.extend(
        [
            "",
            "## Startup and runtime blockers",
            "",
            "| Dependency | Distribution | First reference |",
            "|---|---|---|",
        ]
    )
    if blockers:
        for record in blockers:
            reference = record["references"][0]
            location = f"{reference['source']}:{reference['line']}"
            escaped_path = str(record["path"]).replace("|", "\\|")
            lines.append(f"| `{escaped_path}` | {record['distribution']} | `{location}` |")
    else:
        lines.append("| None | All runtime-critical dependencies are tracked. | — |")

    lines.extend(
        [
            "",
            "## Complete dependency list",
            "",
            "| Dependency | Requirement | Distribution | References |",
            "|---|---|---|---:|",
        ]
    )
    for record in records:
        escaped_path = str(record["path"]).replace("|", "\\|")
        lines.append(
            f"| `{escaped_path}` | {record['requirement']} | "
            f"{record['distribution']} | {len(record['references'])} |"
        )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero when a runtime-critical dependency is not tracked.",
    )
    arguments = parser.parse_args()

    root = Path(__file__).resolve().parents[1]
    tracked = git_lines(root, "ls-files")
    dependencies = collect_dependencies(root, tracked)
    ignored = git_lines(root, "ls-files", "--others", "--ignored", "--exclude-standard")
    records = [
        classify(root, dependencies[path], tracked, ignored)
        for path in sorted(dependencies, key=str.casefold)
    ]

    output_directory = root / "docs" / "assets"
    output_directory.mkdir(parents=True, exist_ok=True)
    json_path = output_directory / "runtime_asset_inventory.json"
    markdown_path = output_directory / "RUNTIME_ASSET_INVENTORY.md"
    payload = {
        "schema_version": 1,
        "generator": "tools/inventory_runtime_assets.py",
        "dependencies": records,
    }
    json_path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    markdown_path.write_text(markdown_report(records), encoding="utf-8")

    blockers = [
        record
        for record in records
        if record["requirement"] == "Runtime-critical" and not record["tracked"]
    ]
    print(
        "RUNTIME_ASSET_INVENTORY_OK "
        f"dependencies={len(records)} runtime_blockers={len(blockers)}"
    )
    return 1 if arguments.check and blockers else 0


if __name__ == "__main__":
    sys.exit(main())
